apiVersion: apps/v1
kind: Ingress
metadata:
  name: vote
  namespace: vote
spec:
  rules:
  - host: guestbook.demo
    http:
      paths:
      - backend:
          serviceName: guestbook-ui
          servicePort: 80
        path: /